{{- $chartName := include "pycsw.name" . -}}
{{- if .Values.rasterCommon.authentication.opa.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-envoy
data:
  envoy.yaml: |-
{{ tpl (.Files.Get "config/envoy.yaml") . | indent 4 }}
{{- end }}
