{{- $chartName := include "pycsw.name" . -}}
{{- if .Values.rasterCommon.authentication.opa.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-opa
data:
  policy.rego: |-
{{ tpl (.Files.Get "config/policy.rego") . | b64enc | indent 4 }}
{{- end }}
