{{- if .Values.nginx.enabled -}}
{{- $chartName := include "pycsw.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-configmap
  labels:
    app: {{ .Release.Name }}-{{ $chartName }}
    component: nginx-configmap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  jwt.js: {{ .Files.Get "config/jwt.js" | quote }}
  log_format.conf: {{ tpl (.Files.Get "config/log_format.conf") . | quote }}
  default.conf: {{ tpl (.Files.Get "config/default.conf") . | quote }}
  nginx.conf: {{ .Files.Get "config/nginx.conf" | quote }}
{{- end }}
