{{- if .Values.nginx.enabled -}}
{{- $chartName := include "pycsw.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-configmap
  labels:
    app: {{ .Release.Name }}-{{ $chartName }}
    component: nginx-configmap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  NGINX_CONFIG: {{ tpl (.Files.Get "config/nginx.conf") . | quote }}
  NGINX_ROOT_CONFIG: {{ .Files.Get "config/nginx_root.conf" | quote }}
{{- end }}
