{{- $releaseName := .Release.Name -}}
{{- $chartName := include "pycsw.name" . -}}
{{- $cloudProviderFlavor := include "pycsw.cloudProviderFlavor" . -}}
{{ $targetPort := ternary "external" "internal" .Values.rasterCommon.authentication.opa.enabled }}

{{- if and (and (.Values.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.route.enabled) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-nginx-route
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
    {{- if .Values.route.timeout.enabled }}
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout.duration }}
    {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  path:  {{ .Values.route.path | default "/" }}
  port:
    targetPort: {{ $targetPort }}
  to:
    kind: Service
    name: {{ $releaseName }}-{{ $chartName }}-nginx
  {{- if .Values.route.https }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- if .Values.route.useCert }}
    certificate: {{ .Files.Get "config/cert.pem" | quote }}
    key: {{ .Files.Get "config/key.pem" | quote }}
    caCertificate: {{ .Files.Get "config/cacert.pem" | quote }}
    {{- end }}
  {{- end -}}
{{- end -}}
