static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.nginx.envoy.port }}
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.File
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: "/dev/null"
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service
                http_filters:
                  - name: envoy.filters.http.jwt_authn
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                      providers:
                        map-colonies-jwt:
                          local_jwks:
                            filename: /keys/mapColonies.jwks
                          forward: true #keep the jwt (if header is used) 
                          from_headers:
                            - name: {{ .Values.nginx.opa.customHeaderName }}
                          from_params:
                            - token
                          jwt_cache_config:
                            jwt_cache_size: 100
                          payload_in_metadata: map_colonies_token_payload
                      rules:
                        - match:
                            prefix: "/"
                          requires:
                            provider_name: "map-colonies-jwt"
                      bypass_cors_preflight: true # all cors preflight requests without auth 
                  - name: envoy.filters.http.set_metadata
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.set_metadata.v3.Config
                      metadata_namespace: map_colonies
                      value: 
                        domain: {{ .Values.nginx.envoy.requestedDomain }}
                  - name: envoy.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      transport_api_version: V3
                      with_request_body:
                        max_request_bytes: {{ .Values.nginx.envoy.maxRequestBytes }}
                        allow_partial_message: true
                      failure_mode_allow: false
                      grpc_service:
                        google_grpc:
                          target_uri: localhost:{{ .Values.nginx.opa.port }}
                          stat_prefix: ext_authz
                        timeout: 0.5s
                      metadata_context_namespaces:
                        - map_colonies
                        - envoy.filters.http.jwt_authn
                  - name: envoy.filters.http.router
  clusters:
    - name: service
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: {{ .Values.nginx.nginxTargetPort }}
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        envoy:
          resource_limits:
            listeners:
              example_listener_name:
                connection_limit: 10000
        overload:
          global_downstream_max_connections: 50000
