apiVersion: v2
name: pycsw
description: A Helm chart for pycsw service
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: nginx
    version: 1.1.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
