apiVersion: v1
data:
  pycsw.cfg: |+
    [server]
{{ if .Values.pycsw.config.server.home }}    home={{ .Values.pycsw.config.server.home }}
{{ end }}{{ if .Values.pycsw.config.server.url }}    url={{ .Values.pycsw.config.server.url }}
{{ end }}{{ if .Values.pycsw.config.server.mimetype }}    mimetype={{ .Values.pycsw.config.server.mimetype }}
{{ end }}{{ if .Values.pycsw.config.server.encoding }}    encoding={{ .Values.pycsw.config.server.encoding }}
{{ end }}{{ if .Values.pycsw.config.server.language }}    language={{ .Values.pycsw.config.server.language }}
{{ end }}{{ if .Values.pycsw.config.server.maxrecords }}    maxrecords={{ .Values.pycsw.config.server.maxrecords }}
{{ end }}{{ if .Values.pycsw.config.server.loglevel }}    loglevel={{ .Values.pycsw.config.server.loglevel }}
{{ end }}{{ if .Values.pycsw.config.server.logfile }}    logfile={{ .Values.pycsw.config.server.logfile }}
{{ end }}{{ if .Values.pycsw.config.server.ogc_schemas_base }}    ogc_schemas_base={{ .Values.pycsw.config.server.ogc_schemas_base }}
{{ end }}{{ if .Values.pycsw.config.server.federatedcatalogues }}    federatedcatalogues={{ .Values.pycsw.config.server.federatedcatalogues }}
{{ end }}{{ if .Values.pycsw.config.server.pretty_print }}    pretty_print={{ .Values.pycsw.config.server.pretty_print }}
{{ end }}{{ if .Values.pycsw.config.server.gzip_compresslevel }}    gzip_compresslevel={{ .Values.pycsw.config.server.gzip_compresslevel }}
{{ end }}{{ if .Values.pycsw.config.server.domainquerytype }}    domainquerytype={{ .Values.pycsw.config.server.domainquerytype }}
{{ end }}{{ if .Values.pycsw.config.server.domaincounts }}     domaincounts={{ .Values.pycsw.config.server.domaincounts }}
{{ end }}{{ if .Values.pycsw.config.server.spatial_ranking }}    spatial_ranking={{ .Values.pycsw.config.server.spatial_ranking }}
{{ end }}{{ if .Values.pycsw.config.server.profiles }}    profiles={{ .Values.pycsw.config.server.profiles }}
{{ end }}{{ if .Values.pycsw.config.server.workers }}    workers={{ .Values.pycsw.config.server.workers }}
{{ end }}
    [manager]
{{ if .Values.pycsw.config.manager.transactions }}    transactions={{ .Values.pycsw.config.manager.transactions }}
{{ end }}{{ if .Values.pycsw.config.manager.allowed_ips }}    allowed_ips={{ .Values.pycsw.config.manager.allowed_ips }}
{{ end }}{{ if .Values.pycsw.config.manager.csw_harvest_pagesize }}    csw_harvest_pagesize={{ .Values.pycsw.config.manager.csw_harvest_pagesize }}
{{ end }}
    [metadata:main]
{{ if .Values.pycsw.config.metadata.identification_title }}    identification_title={{ .Values.pycsw.config.metadata.identification_title }}
{{ end }}{{ if .Values.pycsw.config.metadata.identification_abstract }}    identification_abstract={{ .Values.pycsw.config.metadata.identification_abstract }}
{{ end }}{{ if .Values.pycsw.config.metadata.identification_keywords }}    identification_keywords={{ .Values.pycsw.config.metadata.identification_keywords }}
{{ end }}{{ if .Values.pycsw.config.metadata.identification_keywords_type }}    identification_keywords_type={{ .Values.pycsw.config.metadata.identification_keywords_type }}
{{ end }}{{ if .Values.pycsw.config.metadata.identification_fees }}    identification_fees={{ .Values.pycsw.config.metadata.identification_fees }}
{{ end }}{{ if .Values.pycsw.config.metadata.identification_accessconstraints }}    identification_accessconstraints={{ .Values.pycsw.config.metadata.identification_accessconstraints }}
{{ end }}{{ if .Values.pycsw.config.metadata.provider_name }}    provider_name={{ .Values.pycsw.config.metadata.provider_name }}
{{ end }}{{ if .Values.pycsw.config.metadata.provider_url }}    provider_url={{ .Values.pycsw.config.metadata.provider_url }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_name }}    contact_name={{ .Values.pycsw.config.metadata.contact_name }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_position }}    contact_position={{ .Values.pycsw.config.metadata.contact_position }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_address }}    contact_address={{ .Values.pycsw.config.metadata.contact_address }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_city }}    contact_city={{ .Values.pycsw.config.metadata.contact_city }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_stateorprovince }}    contact_stateorprovince={{ .Values.pycsw.config.metadata.contact_stateorprovince }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_postalcode }}    contact_postalcode={{ .Values.pycsw.config.metadata.contact_postalcode }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_country }}    contact_country={{ .Values.pycsw.config.metadata.contact_country }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_phone }}    contact_phone={{ .Values.pycsw.config.metadata.contact_phone }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_fax }}    contact_fax={{ .Values.pycsw.config.metadata.contact_fax }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_email }}    contact_email={{ .Values.pycsw.config.metadata.contact_email }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_url }}    contact_url={{ .Values.pycsw.config.metadata.contact_url }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_hours }}    contact_hours={{ .Values.pycsw.config.metadata.contact_hours }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_instructions }}    contact_instructions={{ .Values.pycsw.config.metadata.contact_instructions }}
{{ end }}{{ if .Values.pycsw.config.metadata.contact_role }}    contact_role={{ .Values.pycsw.config.metadata.contact_role }}
{{ end }}
    [repository]
{{ if .Values.pycsw.config.repository.database }}    database={{ .Values.pycsw.config.repository.database }}
{{ end }}{{ if .Values.pycsw.config.repository.mappings }}    mappings={{ .Values.pycsw.config.repository.mappings }}
{{ end }}{{ if .Values.pycsw.config.repository.table }}    table={{ .Values.pycsw.config.repository.table }}
{{ end }}{{ if .Values.pycsw.config.repository.filter }}    filter={{ .Values.pycsw.config.repository.filter }}
{{ end }}
    [metadata:inspire]
{{ if .Values.pycsw.config.inspire.enabled }}    enabled={{ .Values.pycsw.config.inspire.enabled }}
{{ end }}{{ if .Values.pycsw.config.inspire.languages_supported }}    languages_supported={{ .Values.pycsw.config.inspire.languages_supported }}
{{ end }}{{ if .Values.pycsw.config.inspire.default_language }}    default_language={{ .Values.pycsw.config.inspire.default_language }}
{{ end }}{{ if .Values.pycsw.config.inspire.date }}    date={{ .Values.pycsw.config.inspire.date }}
{{ end }}{{ if .Values.pycsw.config.inspire.gemet_keywords }}    gemet_keywords={{ .Values.pycsw.config.inspire.gemet_keywords }}
{{ end }}{{ if .Values.pycsw.config.inspire.conformity_service }}    conformity_service={{ .Values.pycsw.config.inspire.conformity_service }}
{{ end }}{{ if .Values.pycsw.config.inspire.contact_name }}    contact_name={{ .Values.pycsw.config.inspire.contact_name }}
{{ end }}{{ if .Values.pycsw.config.inspire.contact_email }}    contact_email={{ .Values.pycsw.config.inspire.contact_email }}
{{ end }}{{ if .Values.pycsw.config.inspire.temp_extent }}    temp_extent={{ .Values.pycsw.config.inspire.temp_extent }}
{{ end }}

kind: ConfigMap
metadata:
  name: {{ .Values.pycsw.configmap_name }}
  namespace: {{ .Values.global.namespace }}
