name: Match chart version and push to ACR

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
env:
  HELM_EXPERIMENTAL_OCI: 1

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-push-docker:
      uses: MapColonies/shared-workflows/.github/workflows/build-and-push-docker.yaml@master
      secrets: inherit
      with:
        scope: raster,3d,dem

  build-and-push-helm-raster:
    defaults:
      run:
        working-directory: ./helm/raster  
      uses: MapColonies/shared-workflows/.github/workflows/build-and-push-helm.yaml@master
      secrets: inherit

  build-and-push-helm-dem:
    defaults:
      run:
        working-directory: ./helm/dem  
      uses: MapColonies/shared-workflows/.github/workflows/build-and-push-helm.yaml@master
      secrets: inherit
